[package]
name = "backlogrs"
version = "0.0.1"
authors = ["Fredrik Sommar <fsommar@kth.se>"]

[[bin]]
name = "main"

[dependencies]
rustc-serialize = "0.2"
postgres = "0.6"
iron = "*"
error = "*"
plugin = "*"
typemap = "*"
