[package]
name = "backlogrs"
version = "0.0.1"
authors = ["Fredrik Sommar <fsommar@kth.se>"]

[dependencies]
rustc-serialize = "0.2"
postgres = "0.6"
iron = "*"
router = "*"
error = "*"
plugin = "*"
typemap = "*"
r2d2 = "0.4"
r2d2_postgres = "0.6"
